### ISSUE TITLE
works/case/站房巡视.html 这里有两个问题

### ISSUE THREAD

**Issue by zhenhappy** [Lin3943/works#1]
第一个就是资源文件最好不要写在head之外, 正确的写法是把css写在head里面, 把style标签写在css之后, js写在body末尾, script写在js之后

第二个就是用了rem单位, 但是没有声明基准, 如果是pc端的页面一般不用rem单位, 移动端才用

**Comment by Lin3943** [comment]
一：这个是一个同事萌新写的，我之前还没教他这些规则，他是做了一个，然后其他的都用这个为模板复制的，所以所有的那些都错了，我的我自己知道
二：嗯，知道，我下载了一个reset.css以后要使用rem单位，会先声明reset.css引用的

**Comment by zhenhappy** [comment]
> 一：这个是一个同事萌新写的，我之前还没教他这些规则，他是做了一个，然后其他的都用这个为模板复制的，所以所有的那些都错了，我的我自己知道
> 二：嗯，知道，我下载了一个reset.css以后要使用rem单位，会先声明reset.css引用的

建议用[normalize.css](https://necolas.github.io/normalize.css/)代替reset.css
